version: "3.9"
services:
  node_backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile 
    network_mode: "host"
   
  auth_backend:
    container_name: auth_service
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    network_mode: "host"
  
  frontend-server:
    container_name: frontend-server
    build: 
      context: ./frontend-server
      dockerfile: Dockerfile
    network_mode: "host"
